---
apiVersion: "apiextensions.k8s.io/v1"
kind: "CustomResourceDefinition"
metadata:
  name: "frontdoors.fdingress.com"
spec:
  group: "fdingress.com"
  scope: "Namespaced"
  names:
    plural: "frontdoors"
    singular: "frontdoor"
    kind: "Frontdoor"
    shortNames:
      - fdid
  versions: 
    - name: "v1alpha1"
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          required: ["spec"]
          type: object
          properties:
            spec:
              type: object
              required: ["frontdoorId"]
              properties:
                frontdoorId:
                  type: "string"

---
apiVersion: "apiextensions.k8s.io/v1"
kind: "CustomResourceDefinition"
metadata:
  name: "ipaddresses.fdingress.com"
spec:
  group: "fdingress.com"
  scope: "Namespaced"
  names:
    plural: "ipaddresses"
    singular: "ipaddress"
    kind: "IpAddress"
    shortNames:
      - ipa
  versions:
    - name: "v1alpha1"
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          required: ["spec"]
          type: object
          properties:
            spec:
              required: ["ipAddress"]
              type: object
              properties:
                ipAddress:
                  type: "string"